name: Docker Image Push to Kubernetes OCI

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    if: "!contains(github.event.head_commit.message, '[skip ci]')" # Skip if the commit message contains '[skip ci]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install OCI CLI
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip3 install oci-cli
          oci --version

      - name: Configure OCI CLI
        run: |
          mkdir -p ~/.oci && echo "${{ secrets.OCI_CONFIG }}" > ~/.oci/config
          echo "${{ secrets.OCI_PRIVATE_KEY }}" > ~/.oci/oci_api_key.pem
          chmod 600 ~/.oci/config ~/.oci/oci_api_key.pem

      - name: Validate OCI CLI
        run: |
          oci iam region list

      - name: Build Docker image
        run: |
          COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          docker build -t taskmaster:${COMMIT_SHA} .

      - name: Log in to OCI Registry
        env:
          OCI_AUTHTOKEN: ${{ secrets.OCI_AUTHTOKEN }}
        run: |
          echo $OCI_AUTHTOKEN | docker login ${{ secrets.OCI_REGION }}.ocir.io -u ${{ secrets.OCI_NAMESPACE }}/${{ secrets.OCI_USERNAME }} --password-stdin

      - name: Tag Docker image
        run: |
          COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          docker tag taskmaster:${COMMIT_SHA} ${{ secrets.OCI_REGION }}.ocir.io/${{ secrets.OCI_NAMESPACE }}/taskmaster:${COMMIT_SHA}

      - name: Push Docker image to OCI Registry
        run: |
          COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          for i in {1..5}; do
            docker push ${{ secrets.OCI_REGION }}.ocir.io/${{ secrets.OCI_NAMESPACE }}/taskmaster:${COMMIT_SHA} && break || sleep 60;
          done

      - name: Verify Docker Image
        run: |
          COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          docker pull ${{ secrets.OCI_REGION }}.ocir.io/${{ secrets.OCI_NAMESPACE }}/taskmaster:${COMMIT_SHA}
          docker images | grep taskmaster

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Configure kubectl
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          mkdir -p $HOME/.kube
          echo "${KUBECONFIG}" > $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config
          kubectl config view
          kubectl get nodes

      - name: Update Deployment YAML
        run: |
          COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          sed -i "s|image: .*/taskmaster:.*|image: ${{ secrets.OCI_REGION }}.ocir.io/${{ secrets.OCI_NAMESPACE }}/taskmaster:${COMMIT_SHA}|g" taskmaster.yaml
          cat taskmaster.yaml

      - name: Apply Kubernetes Configuration
        run: |
          kubectl apply -f taskmaster.yaml
          kubectl rollout status deployment/taskmaster

      - name: Verify Deployed Images
        run: |
          echo "Verifying deployed images in Kubernetes..."
          kubectl get pods -o jsonpath="{.items[*].spec.containers[*].image}" -l app=taskmaster

      - name: Check deployment status
        run: |
          sleep 40
          kubectl get pods -l app=taskmaster
          kubectl describe deployment taskmaster
          kubectl describe pods -l app=taskmaster

      - name: Get LoadBalancer IP
        id: get_ip
        run: |
          IP=$(kubectl get services taskmaster-lb -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          echo "LoadBalancer IP: $IP"
          echo "::set-output name=ip::$IP"

      - name: Write LoadBalancer IP to file
        run: |
          echo "The new LoadBalancer IP address is: ${{ steps.get_ip.outputs.ip }}" > loadbalancer-ip.txt
          cat loadbalancer-ip.txt

      - name: Commit taskmaster.yaml changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add taskmaster.yaml
          git commit -m "Update taskmaster.yaml with new image tag [skip ci]"

      - name: Commit and push LoadBalancer IP file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add loadbalancer-ip.txt
          git commit -m "Update LoadBalancer IP address [skip ci]" || echo "No changes to commit"
          git pull --rebase origin main
          git push origin main
