name: Docker Image Push to Kubernetes OCI

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    if: "!contains(github.event.head_commit.message, '[skip ci]')" # Skip if the commit message contains '[skip ci]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install OCI CLI
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip3 install oci-cli
          oci --version

      - name: Configure OCI CLI
        run: |
          mkdir -p ~/.oci && echo "${{ secrets.OCI_CONFIG }}" > ~/.oci/config
          echo "${{ secrets.OCI_PRIVATE_KEY }}" > ~/.oci/oci_api_key.pem
          chmod 600 ~/.oci/config ~/.oci/oci_api_key.pem

      - name: Validate OCI CLI
        run: |
          oci iam region list

      - name: Build Docker image
        run: |
          docker build -t todochat .

      - name: Log in to OCI Registry
        env:
          OCI_AUTHTOKEN: ${{ secrets.OCI_AUTHTOKEN }}
        run: |
          echo $OCI_AUTHTOKEN | docker login ${{ secrets.OCI_REGION }}.ocir.io -u ${{ secrets.OCI_NAMESPACE }}/${{ secrets.OCI_USERNAME }} --password-stdin

      - name: Tag Docker image
        run: |
          docker tag todochat ${{ secrets.OCI_REGION }}.ocir.io/${{ secrets.OCI_NAMESPACE }}/todochat:latest

      - name: Push Docker image to OCI Registry
        run: |
          for i in {1..5}; do
            docker push ${{ secrets.OCI_REGION }}.ocir.io/${{ secrets.OCI_NAMESPACE }}/todochat:latest && break || sleep 60;
          done

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Configure kubectl
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          mkdir -p $HOME/.kube
          echo "${KUBECONFIG}" > $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config
          kubectl config view
          kubectl get nodes

      - name: Deploy to Kubernetes
        run: |
          kubectl delete -f taskmaster.yaml --ignore-not-found=true
          kubectl create -f taskmaster.yaml

      - name: Check deployment status
        run: |
          sleep 40
          kubectl get pods
          kubectl get services

      - name: Get LoadBalancer IP
        id: get_ip
        run: |
          IP=$(kubectl get services | grep LoadBalancer | awk '{print $4}')
          echo "LoadBalancer IP: $IP"
          echo "::set-output name=ip::$IP"

      - name: Write LoadBalancer IP to file
        run: |
          echo "The new LoadBalancer IP address is: ${{ steps.get_ip.outputs.ip }}" > loadbalancer-ip.txt

      - name: Commit and push LoadBalancer IP file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add loadbalancer-ip.txt
          git commit -m "Update LoadBalancer IP address [skip ci]"
          git pull --rebase origin main
          git push origin main

