name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Install dependencies
      run: mvn install -DskipTests

    - name: Run AuthServiceTest
      run: mvn -Dtest=AuthServiceTest test

    - name: Run DeveloperServiceTest
      run: mvn -Dtest=DeveloperServiceTest test

    - name: Run ProjectServiceTest
      run: mvn -Dtest=ProjectServiceTest test

    - name: Run TaskServiceTest
      run: mvn -Dtest=TaskServiceTest test
